version: "3.8"
services:
  mongo:
    image: mongo:5.0
    container_name: mongo_voyager
    env_file: ./.env
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./database/db:/data/db
      - ./database/dev.archive:/Databases/dev.archive
      - ./database/production:/Databases/production
  mongo-express:
    image: mongo-express
    container_name: mexpress_voyager
    env_file: ./.env
    links:
      - mongo_voyager
    restart: unless-stopped
    ports:
      - "8081:8081"
  redis:
    image: redis:6.2.6
    container_name: redis_voyager
    restart: unless-stopped
    ports:
      - "6379:6379"
    env_file: ./.env
    volumes:
      - ./database/redis:/data
